<?php

return [
    'site' => [
        'name' => (string) env('SITE_NAME', 'Goglobal Yatra'),
        'base_url' => (string) env('SITE_BASE_URL', ''),
        'tagline' => (string) env('SITE_TAGLINE', 'Inbound and Outbound Travel Packages'),
        'logo' => (string) env('SITE_LOGO', 'assets/images/goglobal-yatra-logo.png'),
        'topbar_phone' => (string) env('SITE_PHONE', '+977-9851453377'),
        'topbar_landline' => (string) env('SITE_LANDLINE', '+977-1-4508777'),
        'topbar_email' => (string) env('SITE_EMAIL', 'info@goglobalyatra.com'),
        'address' => (string) env('SITE_ADDRESS', 'Thamel, Kathmandu, Nepal'),
    ],
    'mail' => [
        'to_email' => (string) env('MAIL_TO_EMAIL', 'info@goglobalyatra.com'),
        'from_email' => (string) env('MAIL_FROM_EMAIL', 'info@goglobalyatra.com'),
        'from_name' => (string) env('MAIL_FROM_NAME', 'Goglobal Yatra Website'),
        'mailer' => (string) env('MAIL_MAILER', 'mail'),
        'host' => (string) env('MAIL_HOST', 'smtp.example.com'),
        'port' => (int) env('MAIL_PORT', 587),
        'username' => (string) env('MAIL_USERNAME', 'smtp-user'),
        'password' => (string) env('MAIL_PASSWORD', 'smtp-password'),
        'encryption' => (string) env('MAIL_ENCRYPTION', 'tls'),
    ],
    'search_filters' => [
        'persons' => ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'destinations' => [
            'Europe Tour',
            'Thailand Tour',
            'Bali Tour',
            'Malaysia Tour',
            'China Tour',
            'Dubai',
            'Singapore',
            'Vietnam',
            'Sri Lanka',
            'Maldives',
        ],
        'durations' => ['2-5 days', '5-7 days', 'More than a week', 'More than 10 days'],
    ],
    'banners' => [
        [
            'id' => 1,
            'slug' => 'europe-tour',
            'title' => 'Explore Europe with Curated Multi-City Tours',
            'image_url' => 'assets/images/europe.jpg',
            'button_text' => 'View Europe Packages',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 2,
            'slug' => 'thailand-tour',
            'title' => 'Thailand Escapes: Beaches, Culture and City Life',
            'image_url' => 'assets/images/thailand.jpg',
            'button_text' => 'Plan Thailand Tour',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 3,
            'slug' => 'bali-tour',
            'title' => 'Bali Holiday with Scenic Temples and Island Resorts',
            'image_url' => 'assets/images/bali.jpg',
            'button_text' => 'See Bali Tours',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 4,
            'slug' => 'malaysia-tour',
            'title' => 'Malaysia Tour with Kuala Lumpur and Beyond',
            'image_url' => 'assets/images/malaysia.jpg',
            'button_text' => 'Find Malaysia Packages',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 5,
            'slug' => 'dubai-tour',
            'title' => 'Dubai Luxury and Desert Adventure Holidays',
            'image_url' => 'assets/images/dubai.jpg',
            'button_text' => 'Choose Dubai Plans',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 6,
            'slug' => 'singapore-tour',
            'title' => 'Singapore City Breaks for Family and Couples',
            'image_url' => 'assets/images/singapore.jpg',
            'button_text' => 'Browse Singapore Tours',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 7,
            'slug' => 'vietnam-tour',
            'title' => 'Vietnam Discovery Tours from Hanoi to Ho Chi Minh',
            'image_url' => 'assets/images/vietnam.jpg',
            'button_text' => 'View Vietnam Options',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 8,
            'slug' => 'sri-lanka-tour',
            'title' => 'Sri Lanka Journeys with Nature and Heritage Trails',
            'image_url' => 'assets/images/srilanka.jpg',
            'button_text' => 'Explore Sri Lanka',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
        [
            'id' => 9,
            'slug' => 'maldives-tour',
            'title' => 'Maldives Island Vacations with Beachfront Luxury',
            'image_url' => 'assets/images/maldives.jpg',
            'button_text' => 'Book Maldives Tour',
            'button_url' => 'outbound-packages.php',
            'status' => 1,
        ],
    ],
    'packages' => [
        [
            'id' => 1,
            'slug' => 'europe-tour',
            'title' => 'Europe Tour',
            'duration' => '8 nights / 9 days',
            'short_description' => 'Classic cities, landmarks, and guided group experiences across Europe.',
            'image_url' => 'assets/images/europe.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => true,
        ],
        [
            'id' => 2,
            'slug' => 'thailand-tour',
            'title' => 'Thailand Tour',
            'duration' => '5 nights / 6 days',
            'short_description' => 'Perfect mix of beaches, nightlife, and family-friendly attractions.',
            'image_url' => 'assets/images/thailand.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => true,
        ],
        [
            'id' => 3,
            'slug' => 'bali-tour',
            'title' => 'Bali Tour',
            'duration' => '4 nights / 5 days',
            'short_description' => 'Temple trails, beaches, and curated island leisure activities.',
            'image_url' => 'assets/images/bali.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 4,
            'slug' => 'malaysia-tour',
            'title' => 'Malaysia Tour',
            'duration' => '4 nights / 5 days',
            'short_description' => 'City exploration, shopping, and modern attractions in Malaysia.',
            'image_url' => 'assets/images/malaysia.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 5,
            'slug' => 'dubai-tour',
            'title' => 'Dubai Tour',
            'duration' => '5 nights / 6 days',
            'short_description' => 'Skyline views, desert safaris, and premium city experiences.',
            'image_url' => 'assets/images/dubai.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 13,
            'slug' => 'china-tour',
            'title' => 'China Tour',
            'duration' => '6 nights / 7 days',
            'short_description' => 'Historic landmarks, modern skylines, and rich culture across China.',
            'image_url' => 'assets/images/china.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 6,
            'slug' => 'singapore-tour',
            'title' => 'Singapore Tour',
            'duration' => '4 nights / 5 days',
            'short_description' => 'World-class city breaks with family and couple itineraries.',
            'image_url' => 'assets/images/singapore.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 7,
            'slug' => 'vietnam-tour',
            'title' => 'Vietnam Tour',
            'duration' => '6 nights / 7 days',
            'short_description' => 'History, food, and scenery from north to south Vietnam.',
            'image_url' => 'assets/images/vietnam.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 8,
            'slug' => 'sri-lanka-tour',
            'title' => 'Sri Lanka Tour',
            'duration' => '5 nights / 6 days',
            'short_description' => 'Nature, heritage, and tea-country highlights in one trip.',
            'image_url' => 'assets/images/srilanka.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 9,
            'slug' => 'maldives-tour',
            'title' => 'Maldives Tour',
            'duration' => '4 nights / 5 days',
            'short_description' => 'Island relaxation, beachfront stays, and honeymoon escapes.',
            'image_url' => 'assets/images/maldives.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 10,
            'slug' => 'kathmandu-pokhara-highlights',
            'title' => 'Kathmandu and Pokhara Highlights',
            'duration' => '5 nights / 6 days',
            'short_description' => 'Temples, mountain views, and lakeside city discovery.',
            'image_url' => 'assets/images/nepal-inbound.jpg',
            'type' => 'inbound',
            'status' => 1,
            'is_popular' => false,
        ],
        [
            'id' => 11,
            'slug' => 'nepal-culture-heritage-tour',
            'title' => 'Nepal Culture and Heritage Tour',
            'duration' => '6 nights / 7 days',
            'short_description' => 'Cultural sites, local traditions, and curated city visits.',
            'image_url' => 'assets/images/about-nepal.jpg',
            'type' => 'inbound',
            'status' => 1,
            'is_popular' => true,
        ],
        [
            'id' => 12,
            'slug' => 'scenic-nepal-retreat',
            'title' => 'Scenic Nepal Retreat',
            'duration' => '7 nights / 8 days',
            'short_description' => 'A relaxed scenic escape designed for international travelers.',
            'image_url' => 'assets/images/maldives.jpg',
            'type' => 'inbound',
            'status' => 1,
            'is_popular' => true,
        ],
        [
            'id' => 13,
            'slug' => 'thailand-and-sri-lanka-combo-tour',
            'title' => 'Thailand and Sri Lanka Combo Tour',
            'duration' => '7 nights / 8 days',
            'short_description' => '2 nights Pattaya with coral island tour with lunch and 2 nights Bangkok with city tour. 2 nights in Bentota with sight seeing and 1 night in Colombo with sight seeing.',
            'image_url' => 'assets/images/thailand.jpg',
            'type' => 'outbound',
            'status' => 1,
            'is_popular' => false,
        ],
    ],
];
